FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN apk add --no-cache --virtual .build-deps python3 make g++ && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-timeout 300000 && \
    npm install --production --no-optional --prefer-offline && \
    apk del .build-deps && \
    npm cache clean --force

COPY . .

EXPOSE 8080

ENV NODE_ENV=production

CMD ["node", "--require", "./tracing.js", "app.js"]
